### ISSUE TITLE
Suggestion: Rename objects in a logical order

### ISSUE THREAD

**Issue by vpoguru** [Weisl/simple_renaming_panel#70]
Simple Renaming Panel is so much more powerful than the internal Blender renaming panel. Thank you for this amazing little tool!

It would be great if objects could be renamed in a logical order, e.g. from left to right or from top to bottom. I have the impression that the order is always some sort of random. At least I have not yet found out how the order could be affected.

**Comment by Weisl** [comment]
Hello Christoph.

If I remember right, the renaming order is currently based on the order the object data is stored inside the blender data structure/ file. This appears random, as it does not even correspond to the time of creation necessarily. I have tried to get the order of selection and use that for the renaming order. This is way more complicated than I expected it to be and I did not find an efficient way to do so. 

I haven't thought about another way of sorting. I don't know how useful a renaming order based on location in the 3d view would be. Do you have any examples, where it would bring a benefit?

**Comment by chrschmitz** [comment]
Hello Matthias,

If you have many similar objects and you want to select a subset of them, it may be hard to do so with the box select tool, because everything behind the objects is also selected. Clicking on every single object is also a pain in the neck. Selecting these objects in the outliner would nicely solve this problem.

There is a very old tool (last updated in 2017), which does not seem to work anymore -- sorry for the delayed response, it took me a while to find it -- Batch Renamer from Greg Zaal (http://blog.gregzaal.com/2013/09/07/batch-renamer/, https://github.com/gregzaal/batch-renamer), which offered this option. I do not know, whether his code would work in your plugin.

Best,
Christoph

**Comment by Weisl** [comment]
Doesn't the selection from the outliner get synced to the 3D view? Unfortunately, it is really hard to get the data to form the outliner directly. They have completely independent contexts. You could also have 2 Outliners open with contradicting selection/contexts. 
Thanks for sharing the link. I will check it out, probably I can find something useful.

**Comment by Weisl** [comment]
Objects can now be renamed by selection order
